//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NCBOnlineBank.WebEndpoint1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback MakePaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback ViewTransactionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::NCBOnlineBank.Properties.Settings.Default.NCBOnlineBank_WebEndpoint1_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event VerifyAccountCompletedEventHandler VerifyAccountCompleted;
        
        /// <remarks/>
        public event MakePaymentCompletedEventHandler MakePaymentCompleted;
        
        /// <remarks/>
        public event ViewTransactionCompletedEventHandler ViewTransactionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerifyAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerifyAccount(int customerNumber, int premiseNumber, string category) {
            object[] results = this.Invoke("VerifyAccount", new object[] {
                        customerNumber,
                        premiseNumber,
                        category});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyAccountAsync(int customerNumber, int premiseNumber, string category) {
            this.VerifyAccountAsync(customerNumber, premiseNumber, category, null);
        }
        
        /// <remarks/>
        public void VerifyAccountAsync(int customerNumber, int premiseNumber, string category, object userState) {
            if ((this.VerifyAccountOperationCompleted == null)) {
                this.VerifyAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyAccountOperationCompleted);
            }
            this.InvokeAsync("VerifyAccount", new object[] {
                        customerNumber,
                        premiseNumber,
                        category}, this.VerifyAccountOperationCompleted, userState);
        }
        
        private void OnVerifyAccountOperationCompleted(object arg) {
            if ((this.VerifyAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyAccountCompleted(this, new VerifyAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MakePayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MakePayment(int customerNumber, int premiseNumber, string category, string customerName, int payeeId, decimal payAmount) {
            this.Invoke("MakePayment", new object[] {
                        customerNumber,
                        premiseNumber,
                        category,
                        customerName,
                        payeeId,
                        payAmount});
        }
        
        /// <remarks/>
        public void MakePaymentAsync(int customerNumber, int premiseNumber, string category, string customerName, int payeeId, decimal payAmount) {
            this.MakePaymentAsync(customerNumber, premiseNumber, category, customerName, payeeId, payAmount, null);
        }
        
        /// <remarks/>
        public void MakePaymentAsync(int customerNumber, int premiseNumber, string category, string customerName, int payeeId, decimal payAmount, object userState) {
            if ((this.MakePaymentOperationCompleted == null)) {
                this.MakePaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMakePaymentOperationCompleted);
            }
            this.InvokeAsync("MakePayment", new object[] {
                        customerNumber,
                        premiseNumber,
                        category,
                        customerName,
                        payeeId,
                        payAmount}, this.MakePaymentOperationCompleted, userState);
        }
        
        private void OnMakePaymentOperationCompleted(object arg) {
            if ((this.MakePaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MakePaymentCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ViewTransaction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ViewTransaction(int customerNumber, int premiseNumber, string category, int payeeId, decimal transactionAmount) {
            this.Invoke("ViewTransaction", new object[] {
                        customerNumber,
                        premiseNumber,
                        category,
                        payeeId,
                        transactionAmount});
        }
        
        /// <remarks/>
        public void ViewTransactionAsync(int customerNumber, int premiseNumber, string category, int payeeId, decimal transactionAmount) {
            this.ViewTransactionAsync(customerNumber, premiseNumber, category, payeeId, transactionAmount, null);
        }
        
        /// <remarks/>
        public void ViewTransactionAsync(int customerNumber, int premiseNumber, string category, int payeeId, decimal transactionAmount, object userState) {
            if ((this.ViewTransactionOperationCompleted == null)) {
                this.ViewTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnViewTransactionOperationCompleted);
            }
            this.InvokeAsync("ViewTransaction", new object[] {
                        customerNumber,
                        premiseNumber,
                        category,
                        payeeId,
                        transactionAmount}, this.ViewTransactionOperationCompleted, userState);
        }
        
        private void OnViewTransactionOperationCompleted(object arg) {
            if ((this.ViewTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ViewTransactionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void VerifyAccountCompletedEventHandler(object sender, VerifyAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void MakePaymentCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ViewTransactionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591